"""Add price and remove created_at from orders

Revision ID: b45f9bf9740c
Revises: 8e3888d1cd7a
Create Date: 2025-11-16 20:01:29.294187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45f9bf9740c'
down_revision: Union[str, Sequence[str], None] = '8e3888d1cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('orders', 'created_at')  # ← ДОБАВЬ ЭТУ СТРОКУ
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
